version: '3.7'
#service group
services:
  app-frontend:
    depends_on:
      - app-backend
    image: tibame201020/exam-frontend
    restart: on-failure
    ports:
      - 4200:80
    networks:
      front2back:
  app-backend:
    image: tibame201020/exam-backend
    restart: on-failure
    ports:
      - "12058:12058"
    volumes:
      - ./h2data:/app/h2data
    networks:
      front2back:
networks:
  front2back:
volumes:
  h2data:
