version: '3.7'

services:
  wls14:
    container_name: wls14
    image: tibame201020/weblogic:14
    ports:
      - "7001:7001"
    volumes:
      - ./mysql-connector-java-commercial-8.0.14.jar:/u01/oracle/oracle_common/modules/mysql-connector-java-commercial-8.0.14/mysql-connector-java-commercial-8.0.14.jar
      - ./domain.properties:/u01/oracle/properties/domain.properties
      - ./user_projects:/u01/oracle/user_projects
      - ./home:/home
    environment:
      - TZ=Asia/Taipei
      - ADMINISTRATION_PORT_ENABLED=false
      - DOMAIN_NAME=base_domain
      - DOMAIN_HOME=/u01/oracle/user_projects/domains/base_domain
      - ADMIN_PORT=9002
      - ADMIN_USERNAME=weblogic
      - ADMIN_PASSWORD=welcome1
      - PRODUCTION_MODE=dev
      - DEBUG_FLAG=true
      - DEBUG_PORT=8453
      - JAVA_OPTIONS=-Dweblogic.StdoutDebugEnabled=false
